import { PrismaClient } from "@prisma/client-postgres";

const prisma = new PrismaClient();

const interests = [
  "cloud computing",
  "technology",
  "understand human behaviour",
  "sales/marketing",
  "trading",
  "home interior design",
  "research",
  "teaching",
  "understand human body",
  "content writing",
  "govt. job",
  "service",
  "infrastructure",
  "financial analysis",
  "take risk for profits",
  "entrepreneurship",
  "digital marketing",
  "market research",
  "agriculture",
  "construction management",
  "data analytics",
  "data scientist",
  "industries",
  "information technology",
  "news coverage",
  "social justice",
  "supply chain analysis",
  "game industry",
  "design",
  "web designing",
  "web development",
  "social causes",
  "blockchain",
  "machine learning",
  "excel",
  "sports industry",
  "product life cycle management",
  "sap consultant in mm",
  "project management",
  "navy defence related",
  "oil and gas",
  "biotechnology",
  "software developer",
  "hospitality",
  "salesforce admin",
  "social media marketing",
  "software job",
  "it",
  "urban planning",
  "data entry or telecalling work",
  "mobile app development",
  "geography",
  "geology",
  "statistical programmer",
  "software engineering",
  "gardening",
  "operations",
  "cyber security",
  "application development",
  "higher studies",
  "retailer",
  "litigation & legal service",
  "animation",
  "all fields related to data science",
  "analysis",
  "architecture and construction",
];

const skills = [
  "python",
  "sql",
  "java",
  "critical thinking",
  "analytic thinking",
  "programming",
  "work under pressure",
  "logical skills",
  "problem solving skills",
  "people management",
  "communication skills",
  "accounting skills",
  "plc allen bradley",
  "plc ladder logic",
  "labview",
  "business analysis",
  "end-to-end project management",
  "cross-functional team leadership",
  "requirements gathering",
  "lean six sigma",
  "lean six sigma blackbelt",
  "productivity improvement",
  "c",
  "html",
  "active listening",
  "gathering information",
  "artistic/creative skills",
  "leadership",
  "editing",
  "writing skills",
  "medical knowledge",
  "hr",
  "teaching",
  "cost accounting",
  "team work",
  "tableau",
  "data visualization skills( power bi/ tableau )",
  "machine learning skills",
  "artificial intelligence",
  "matlab",
  "r",
  "designing skills",
  "proeficiency in software like staad pro, etabs",
  "hardware skills",
  "product knowledge",
  "risk management skills",
  "cad/cae(autocad/catia/ansys/proe/seimensnx)",
  "finance related skills",
  "negotiation skills",
  "mass communication",
  "sales",
  "interpersonal skills",
  "wealth management",
  "financial analysis",
  "financial modeling",
  "marketing strategy",
  "financial services",
  "design and analysis of automobile components",
  "vehicle maintenance and reconditioning",
  "design for manufacturer and assemble",
  "creativity skills",
  "excel",
  "teamwork",
  "time management",
  "company secretarial work",
  "legal compliance",
  "interpersonal communication",
  "companies act",
  "indirect taxation",
  "cloud computing",
  "reporting",
  "observation skills",
  "subject knowledge",
  "business knowledge",
  "market study",
  "civil & criminal law",
  "social media marketing",
  "bootstrap",
  "node.js",
  "angular",
  "jira",
  "trello",
  "jquery",
  "javascript",
  "ajax",
  "php",
  "codeignitor",
  "loopback",
  "hospitality",
  "polymerase chain reaction (pcr)",
  "life sciences",
  "protein purification",
  "protein chemistry",
  "protein assays",
  "protein electrophoresis",
  "protein chromatography",
  "western blotting",
  "protein structure prediction",
  "protein kinases",
  "protein characterization",
  "protein engineering",
  "phytochemistry",
  "metabolomics",
  "dna",
  "biochemistry",
  "bioinformatics",
  "cell culture",
  "staad pro",
  "etabs",
  "data science",
  "sap",
  ".net framework",
  "transact",
  "technical machine fitter",
  "c#",
  "good communication skills",
  "client management",
  "business analytics",
  "risk analytics",
  "sas",
  "marketing management",
  "market research",
  "business strategy",
  "commercial banking",
  "portfolio management",
  "supply chain management",
  "business process reengineering",
  "consumer behaviour",
  "long-term customer relationships",
  "retail marketing",
  "financial accounting",
  "credit risk modeling",
  "security analysis",
  "working capital management",
  "strategic marketing",
  "investment banking",
  "structured finance",
  "building rapport",
  "2d/3d animation",
  "oracle",
  "no",
];

async function main() {
  console.log(`Start seeding ...`);

  // Seed Interests
  console.log("Seeding Interests...");
  for (const interest of interests) {
    await prisma.interest.upsert({
      where: { name: interest },
      update: {},
      create: { name: interest },
    });
  }

  // Seed Skills
  console.log("Seeding Skills...");
  for (const skill of skills) {
    await prisma.skill.upsert({
      where: { name: skill },
      update: {},
      create: { name: skill },
    });
  }

  console.log(`Seeding finished.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
